
    let chiese = [
		{"paese": "Bellino", "frazione": "Chiesa", "intitolazione": "S. Giacomo", "posizione": { "indirizzo":"Fr. Chiesa", "CAP": "12030", "lat": 0, "lon": 0}},
		{"paese": "Bellino", "frazione": "Celle", "intitolazione": "S. Spirito", "posizione": { "indirizzo":"Fr. Celle", "CAP": "12030", "lat": 0, "lon": 0}},
		{"paese": "Brossasco", "frazione": "Capoluogo", "intitolazione": "SS. Andrea, Sisto e Madonna della Spina", "posizione": { "indirizzo":"P.zza Parrocchia", "CAP": "12030", "lat": 0, "lon": 0}},
		{"paese": "Casteldelfino", "frazione": "Capoluogo", "intitolazione": "S. Margherita", "posizione": { "indirizzo":"Via Roma, 51", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Costigliole di Saluzzo", "frazione": "Capoluogo", "intitolazione": "S. Maria Maddalena", "posizione": { "indirizzo":"Via Umberto I", "CAP": "12024", "lat": 0, "lon": 0}},
		{"paese": "Costigliole di Saluzzo", "frazione": "", "intitolazione": "Confraternita", "posizione": { "indirizzo":"", "CAP": "", "lat": 0, "lon": 0}},
		{"paese": "Frassino", "frazione": "Capoluogo", "intitolazione": "SS. Stefano e Maurizio", "posizione": { "indirizzo":"Via Vittorio Venerto", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Isasca", "frazione": "Capoluogo", "intitolazione": "S. Massimo", "posizione": { "indirizzo":"Via S. Chiaffredo, 10", "CAP": "12020", "lat": 0, "lon": 0}},	
		{"paese": "Manta", "frazione": "Capoluogo", "intitolazione": "S. Maria degli Angeli", "posizione": { "indirizzo":"P.zza Conte Camillo Benso", "CAP": "12030", "lat": 0, "lon": 0}},
		{"paese": "Melle", "frazione": "Capoluogo", "intitolazione": "SS. Giovanni Battista e Eusebio", "posizione": { "indirizzo":"P.zza don Franco Giacomo, 1", "CAP": "12020", "lat": 0, "lon": 0}},	
		{"paese": "Piasco", "frazione": "Capoluogo", "intitolazione": "S. Giovanni", "posizione": { "indirizzo":"P.zza Martiri della Liberazione, 4C", "CAP": "12026", "lat": 44.569014, "lon": 7.457667}},
		{"paese": "Piasco", "frazione": "S. Antonio", "intitolazione": "S. Antonio", "posizione": { "indirizzo":"Via Rossana, 2A", "CAP": "12026", "lat": 44.560778, "lon": 7.447408,}},
		{"paese": "Piasco", "frazione": "Capoluogo", "intitolazione": "Mad. del Carmine", "posizione": { "indirizzo":"Via Wild", "CAP": "12026", "lat": 44.565972, "lon": 7.455669}},
		{"paese": "Pontechianale", "frazione": "Chianale", "intitolazione": "S. Lorenzo", "posizione": { "indirizzo":"Fraz. Chianale", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Pontechianale", "frazione": "", "intitolazione": "S. Pietro in Vincoli", "posizione": { "indirizzo":"Loc. Chiesa", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Rossana", "frazione": "Capoluogo", "intitolazione": "Parrocchia", "posizione": { "indirizzo":"Via G. Mazzini, 15A", "CAP": "12020", "lat": 44.54293, "lon": 7.43325}},
		{"paese": "Rossana", "frazione": "Mad. delle Grazie", "intitolazione": "Mad. delle Grazie", "posizione": { "indirizzo":"", "CAP": "12020", "lat": 44.52499, "lon": 7.40652}},
		{"paese": "Rossana", "frazione": "Lemma", "intitolazione": "S. Marco", "posizione": { "indirizzo":"", "CAP": "12020", "lat": 44.52075, "lon": 7.38581}},
		{"paese": "Sampeyre", "frazione": "Becetto", "intitolazione": "Natività di Maria V. e S. Eusebio", "posizione": { "indirizzo":"Fr. Becetto", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Sampeyre", "frazione": "Rore", "intitolazione": "S. Nicolao", "posizione": { "indirizzo":"Fr. Rore", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Sampeyre", "frazione": "Capoluogo", "intitolazione": "SS. Pietro e Paolo", "posizione": { "indirizzo":"Via Parrocchia, 2", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Sampeyre", "frazione": "Ricovero", "intitolazione": "", "posizione": { "indirizzo":"", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Sampeyre", "frazione": "Villar", "intitolazione": "S. Maria Assunta", "posizione": { "indirizzo":"Fr. Villar", "CAP": "", "lat": 44.583563, "lon": 7.14217}},
		{"paese": "Valmala", "frazione": "Borgata Chiesa", "intitolazione": "S. Giovanni Battista", "posizione": { "indirizzo":"Borgata Chiesa, 14", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Venasca", "frazione": "Capoluogo", "intitolazione": "Maria Vergine Assunta", "posizione": { "indirizzo":"Via Ruffino, 1", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Venasca", "frazione": "Bricco", "intitolazione": "Visitazione di Maria SS.", "posizione": { "indirizzo":"Loc. Casale Bricco", "CAP": "12020", "lat": 0, "lon": 0}},
		{"paese": "Verzuolo", "frazione": "Falicetto", "intitolazione": "S. Bartolomeo", "posizione": { "indirizzo":"Via Saluzzo, 2", "CAP": "12039", "lat": 0, "lon": 0}},
		{"paese": "Verzuolo", "frazione": "Villanovetta", "intitolazione": "S. Andrea", "posizione": { "indirizzo":"Via Griselda, 4C", "CAP": "12039", "lat": 0, "lon": 0}},
		{"paese": "Verzuolo", "frazione": "Capoluogo", "intitolazione": "S. Maria della Scala", "posizione": { "indirizzo":"C.so Umberto, 200", "CAP": "", "lat": 0, "lon": 0}},
		{"paese": "Verzuolo", "frazione": "Capoluogo", "intitolazione": "SS. Filippo e Giacomo", "posizione": { "indirizzo":"Via del Castello, 8", "CAP": "12039", "lat": 0, "lon": 0}}
	]